/* Auto-generated by scripts/build-web.js — do not edit by hand. */
const CACHE = 'cf-v1.0.0-beta.1-1784598761854';
const ASSETS = [
  "./icons/apple-touch-icon.png",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/icon-maskable-512.png",
  "./index.html",
  "./manifest.webmanifest",
  "./prompts/ARTICLE-IMAGE-5x2-v1.md",
  "./prompts/CAROUSEL-FORGE-v1.md",
  "./prompts/FACEBOOK-PROMPT-POST-v1.md",
  "./prompts/NEON-LISTICLE-CAROUSEL-v1.md",
  "./prompts/TIKTOK-REEL-FORGE-v1.md",
  "./prompts/editorial-os-instagram-carousel-prompt.md"
];

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

// Cache-first for same-origin GETs; falls back to network, then updates the cache.
self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  event.respondWith(
    caches.match(req).then((cached) => {
      const network = fetch(req).then((res) => {
        if (res && res.ok) {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(req, copy));
        }
        return res;
      }).catch(() => cached);
      return cached || network;
    })
  );
});
