#!/usr/bin/env node
/*
 * build-web.js — assemble the deployable PWA into ./web
 *
 * The desktop renderer (src/index.html) is the single source of truth. This
 * script copies it (plus the prompt library and icons) into a self-contained
 * static folder, then writes the PWA manifest and a service worker whose
 * precache list is generated from what actually landed in ./web.
 *
 * Pure Node, no dependencies. Run: npm run build:web
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const WEB = path.join(ROOT, 'web');

function rmrf(p) { fs.rmSync(p, { recursive: true, force: true }); }
function mkdirp(p) { fs.mkdirSync(p, { recursive: true }); }
function copy(src, dest) { mkdirp(path.dirname(dest)); fs.copyFileSync(src, dest); }
function copyDir(src, dest) {
  mkdirp(dest);
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, entry.name);
    const d = path.join(dest, entry.name);
    if (entry.isDirectory()) copyDir(s, d);
    else copy(s, d);
  }
}
function listFiles(dir, base = dir) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...listFiles(full, base));
    else out.push('./' + path.relative(base, full).split(path.sep).join('/'));
  }
  return out;
}

const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));

// 1) Clean + recreate ./web
rmrf(WEB);
mkdirp(WEB);

// 2) Copy app shell, prompts, icons
copy(path.join(ROOT, 'src', 'index.html'), path.join(WEB, 'index.html'));
copyDir(path.join(ROOT, 'prompts'), path.join(WEB, 'prompts'));
copyDir(path.join(ROOT, 'assets', 'icons'), path.join(WEB, 'icons'));

// 3) Manifest
const manifest = {
  name: 'Lucedale Content Forge',
  short_name: 'Content Forge',
  description: pkg.description,
  id: '/',
  start_url: './index.html',
  scope: './',
  display: 'standalone',
  orientation: 'any',
  background_color: '#08090b',
  theme_color: '#08090b',
  icons: [
    { src: 'icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
    { src: 'icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
    { src: 'icons/icon-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' }
  ]
};
fs.writeFileSync(path.join(WEB, 'manifest.webmanifest'), JSON.stringify(manifest, null, 2));

// 4) Service worker — precache everything currently in ./web (except the SW itself)
const version = 'cf-v' + pkg.version + '-' + Date.now();
const assets = listFiles(WEB).filter((f) => f !== './service-worker.js');
const sw = `/* Auto-generated by scripts/build-web.js — do not edit by hand. */
const CACHE = '${version}';
const ASSETS = ${JSON.stringify(assets, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

// Cache-first for same-origin GETs; falls back to network, then updates the cache.
self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  event.respondWith(
    caches.match(req).then((cached) => {
      const network = fetch(req).then((res) => {
        if (res && res.ok) {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(req, copy));
        }
        return res;
      }).catch(() => cached);
      return cached || network;
    })
  );
});
`;
fs.writeFileSync(path.join(WEB, 'service-worker.js'), sw);

// 5) Deploy notes
fs.writeFileSync(path.join(WEB, 'README.md'), `# Lucedale Content Forge — Web / PWA build

Generated by \`npm run build:web\`. This folder is a self-contained static site.

## Test on your phone (same Wi-Fi)
\`\`\`bash
cd web
npx --yes serve .        # or: python3 -m http.server 8080
\`\`\`
Open the printed \`http://<your-computer-ip>:PORT\` URL on your phone.
In Safari (iOS): Share → **Add to Home Screen**.
In Chrome (Android): menu → **Install app** / **Add to Home screen**.

## Deploy (public HTTPS — required for install + offline)
Drag this \`web\` folder onto **Netlify Drop** (app.netlify.com/drop), or use
Vercel / GitHub Pages / Cloudflare Pages. Any static host works.

Data (projects, brand defaults) is stored in the browser via localStorage.
The full prompt library and app shell are cached for offline use.
`);

console.log('Built ./web:');
console.log('  files : ' + listFiles(WEB).length);
console.log('  cache : ' + assets.length + ' assets precached');
console.log('  ver   : ' + version);
